name: Release UI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "ui-v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build_on_windows:
    env:
      PUPPETEER_SKIP_DOWNLOAD: 'true'
      VITE_APP_GTAG_API_SECRET: ${{ secrets.VITE_APP_GTAG_API_SECRET }}
      VITE_APP_GTAG_MEASUREMENT_ID: ${{ secrets.VITE_APP_GTAG_MEASUREMENT_ID }}
    runs-on: windows-2022
    permissions: write-all

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
    
    - name: Install dependencies
      run: |
        npm i -g pnpm@9
        pnpm install --filter packages/ui...

    - name: Build
      env:
        ELECTRON_MIRROR: https://github.com/electron/electron/releases
      run: pnpm --filter packages/ui run build:make-dist-for-current-platform

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary-geekgeekrun-ui-windows-x64-${{ github.sha }}
        path: |
          ${{ github.workspace }}/packages/ui/dist/*
        overwrite: true

  build_on_macos:
    strategy:
      matrix:
        platform:
          - os: macos-13 # for x64 build
            arch: x64
          - os: macos-15 # for arm64 build
            arch: arm64
    env:
      PUPPETEER_SKIP_DOWNLOAD: 'true'
      VITE_APP_GTAG_API_SECRET: ${{ secrets.VITE_APP_GTAG_API_SECRET }}
      VITE_APP_GTAG_MEASUREMENT_ID: ${{ secrets.VITE_APP_GTAG_MEASUREMENT_ID }}
    runs-on: ${{ matrix.platform.os }}
    permissions: write-all

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout source
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
    
    - name: Install dependencies
      run: |
        npm i -g pnpm@9
        pnpm install --filter packages/ui...

    - name: Build
      env:
        ELECTRON_MIRROR: https://github.com/electron/electron/releases
      run: pnpm --filter packages/ui run build:make-dist-for-current-platform

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary-geekgeekrun-ui-macos-${{ matrix.platform.arch }}-${{ github.sha }}
        path: |
          ${{ github.workspace }}/packages/ui/dist/*
        overwrite: true

  build_on_linux:
    env:
      PUPPETEER_SKIP_DOWNLOAD: 'true'
      VITE_APP_GTAG_API_SECRET: ${{ secrets.VITE_APP_GTAG_API_SECRET }}
      VITE_APP_GTAG_MEASUREMENT_ID: ${{ secrets.VITE_APP_GTAG_MEASUREMENT_ID }}
    runs-on: ubuntu-22.04
    permissions: write-all

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout source
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
    
    - name: Install dependencies
      run: |
        npm i -g pnpm@9
        pnpm install --filter packages/ui...

    - name: Build
      env:
        ELECTRON_MIRROR: https://github.com/electron/electron/releases
      run: pnpm --filter packages/ui run build:make-dist-for-current-platform

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary-geekgeekrun-ui-linux-x64-${{ github.sha }}
        path: |
          ${{ github.workspace }}/packages/ui/dist/*

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    needs:
      - build_on_linux
      - build_on_macos
      - build_on_windows

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          path: geekgeekrun-ui@${{ github.sha }}
          pattern: binary-geekgeekrun-ui-*
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -llR geekgeekrun-ui@${{ github.sha }}

      - name: Create release for public
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          allowUpdates: true
          artifacts: geekgeekrun-ui@${{ github.sha }}/*
          tag: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          skipIfMissing: true
